const ADMIN_OVERRIDE_KEY = window.HOMESTEAD_ADMIN_META?.key || "homestead_admin_overrides";
const DEFAULT_CONFIG = window.HOMESTEAD_DEFAULT_CONFIG || {};
let siteConfig = JSON.parse(JSON.stringify(DEFAULT_CONFIG));
let currentLang = localStorage.getItem("preferred_lang") || (typeof navigator !== "undefined" && String(navigator.language || "").toLowerCase().startsWith("ko") ? "ko" : "en");
let activeRoomFilter = "all";
let isDrawerOpen = false;
let lastFocusedElement = null;
let heroCarouselTimer = null;
let heroSlideIndex = 0;

function clone(value) { return JSON.parse(JSON.stringify(value || {})); }
function isObject(value) { return value && typeof value === "object" && !Array.isArray(value); }
function deepMerge(base, override) { if (Array.isArray(override)) return override.map((item) => clone(item)); if (!isObject(override)) return override === undefined ? base : override; const result = isObject(base) ? { ...base } : {}; Object.entries(override).forEach(([key, value]) => { if (Array.isArray(value)) result[key] = value.map((item) => clone(item)); else if (isObject(value)) result[key] = deepMerge(result[key], value); else result[key] = value; }); return result; }
function normalizeEnglishPrice(value) { if (typeof value !== "string") return value; const trimmed = value.trim(); const match = trimmed.match(/^(\$\d+(?:\.\d+)?\/day)\s*(?:[\/·�]\s*)?\(?(\$\d+\/month)\)?$/); if (match) return `${match[1]} (${match[2]})`; return trimmed.replace(/\s*[·�]\s*/g, " ").replace(/\s*\/\s*(\$\d+\/month)$/g, " ($1)"); }
function sanitizeHeroNotes(notes) { if (!Array.isArray(notes)) return []; return notes.map((note) => String(note || "").replace(/\s+/g, " ").trim()).filter((note) => { const lower = note.toLowerCase(); return note && !lower.includes("since 2007") && !lower.includes("refundable incidental deposit"); }); }
function getBrandTrustLine() { return currentLang === "ko" ? (siteConfig.branding.trustKo || "Since 2007") : (siteConfig.branding.trustEn || "Since 2007"); }
function applyContentRevision(config) { if (config.branding) { config.branding.subtitleKo = "서울의 1인 전용 프라이빗룸"; config.branding.subtitleEn = "Private Room Urban Living"; config.branding.trustKo = "Since 2007"; config.branding.trustEn = "Since 2007"; } const ko = config.pages?.ko; if (ko?.hero) { ko.hero.title = "방배역 도보 2분<br>혼자 쓰는 풀옵션"; if (Array.isArray(ko.hero.chips)) ko.hero.chips = ko.hero.chips.filter((chip) => chip !== "1인실만 운영"); if (Array.isArray(ko.hero.notes)) { ko.hero.notes = ko.hero.notes.filter((note) => note !== "Refundable incidental deposit" && note !== "Since 2007"); } } if (ko?.quickFacts) ko.quickFacts.title = ""; if (ko?.included) ko.included.desc = ""; if (ko?.location) { ko.location.title = ""; if (Array.isArray(ko.location.points)) ko.location.points = ko.location.points.filter((point) => point !== "조용한 단독 거주 분위기를 선호하는 사용자에게 적합"); } if (Array.isArray(config.media?.tierGallery)) config.media.tierGallery.forEach((group) => { group.priceEn = normalizeEnglishPrice(group.priceEn); }); const en = config.pages?.en; if (en?.hero) { en.hero.kicker = "Solo traveler stay · Furnished room · Seoul"; if (Array.isArray(en.hero.notes)) { en.hero.notes = en.hero.notes.filter((note) => note !== "Refundable incidental deposit" && note !== "Since 2007"); } } if (en?.concept) en.concept.desc = ""; if (en?.gallery) en.gallery.desc = ""; if (en?.included) en.included.desc = ""; if (en?.pricing && Array.isArray(en.pricing.rows)) en.pricing.rows.forEach((row) => { row.price = normalizeEnglishPrice(row.price); }); if (en?.process) { en.process.title = "A clear inquiry and payment process"; en.process.desc = ""; if (Array.isArray(en.process.steps) && en.process.steps[3]) { en.process.steps[3].title = "Pay before move-in or in cash at check-in"; en.process.steps[3].copy = "You can pay the refundable incidental deposit and monthly rent by card before move-in, or pay in cash at check-in if you prefer."; } } if (en?.contact) en.contact.mobileCtas = [{ type: "whatsapp", label: "WhatsApp" }, { type: "phone", label: "Call" }, { type: "email", label: "Email" }]; return config; }
function escapeHtml(value) { return String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
function escapeHtmlWithBreaks(value) { return String(value || "").split(/<br\s*\/?>|\n/gi).map((part) => escapeHtml(part)).join("<br>"); }
function getCurrentCopy() { return siteConfig.pages?.[currentLang] || siteConfig.pages?.ko || {}; }
function getBrandTitle() { return currentLang === "ko" ? siteConfig.branding.ko : siteConfig.branding.en; }
function getBrandSubtitle() { return currentLang === "ko" ? siteConfig.branding.subtitleKo : siteConfig.branding.subtitleEn; }
function normalizeHeroImages(images) { const list = Array.isArray(images) ? images.map((item) => String(item || "").trim()).filter(Boolean) : []; if (list.length === 0) list.push("images/room-s-1.jpg"); while (list.length < 3) list.push(list[list.length - 1]); return list.slice(0, 3); }
function normalizePhoneToDigits(phone) { return String(phone || "").replace(/[^\d]/g, ""); }
function isUsableUrl(value) { if (!value || typeof value !== "string") return false; const trimmed = value.trim(); if (!trimmed || trimmed.includes("replace-me")) return false; try { new URL(trimmed, location.origin); return true; } catch (_) { return trimmed.startsWith("#"); } }
function resolveAction(action) { const fallbackHref = "#contact"; if (!action) return { href: fallbackHref, label: "", target: "", rel: "" }; if (action.href) { const href = action.href.trim(); const external = href.startsWith("http"); return { href, label: action.label || "", target: external ? "_blank" : "", rel: external ? "noopener noreferrer" : "" }; } if (action.type === "naver") { if (isUsableUrl(siteConfig.contact.naverUrl)) return { href: siteConfig.contact.naverUrl.trim(), label: action.label || "", target: "_blank", rel: "noopener noreferrer" }; return { href: fallbackHref, label: action.fallbackLabel || action.label || "", target: "", rel: "" }; } if (action.type === "email") return { href: `mailto:${siteConfig.contact.email}`, label: action.label || "", target: "", rel: "" }; if (action.type === "phone") return { href: `tel:${normalizePhoneToDigits(siteConfig.contact.phone)}`, label: action.label || "", target: "", rel: "" }; if (action.type === "whatsapp") { const phone = normalizePhoneToDigits(siteConfig.contact.whatsappNumber || siteConfig.contact.phone); const text = currentLang === "ko" ? encodeURIComponent("안녕하세요. 홈스테이드 서울 객실 가능 여부를 문의드립니다.") : encodeURIComponent("Hello, I would like to ask about room availability at Homestead Seoul."); return { href: `https://wa.me/${phone}?text=${text}`, label: action.label || "", target: "_blank", rel: "noopener noreferrer" }; } if (action.type === "kakao" && isUsableUrl(siteConfig.contact.kakaoUrl)) return { href: siteConfig.contact.kakaoUrl.trim(), label: action.label || "", target: "_blank", rel: "noopener noreferrer" }; return { href: fallbackHref, label: action.label || "", target: "", rel: "" }; }
function getChannelVisual(type) { if (type === "kakao") return { tone: "kakao", badge: "KakaoTalk", icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4.2c-4.75 0-8.6 3.04-8.6 6.8 0 2.42 1.6 4.55 4 5.76l-.93 3.52a.47.47 0 0 0 .72.5l4.13-2.77c.22.02.45.03.68.03 4.75 0 8.6-3.04 8.6-6.79 0-3.77-3.85-6.81-8.6-6.81Z" fill="currentColor"/></svg>' }; if (type === "whatsapp") return { tone: "whatsapp", badge: "WhatsApp", icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.52 3.48A11.86 11.86 0 0 0 12.06 0C5.5 0 .18 5.32.18 11.88c0 2.1.55 4.15 1.58 5.95L0 24l6.37-1.67a11.85 11.85 0 0 0 5.69 1.45h.01c6.55 0 11.88-5.33 11.88-11.89 0-3.18-1.24-6.17-3.43-8.4ZM12.07 21.7h-.01a9.8 9.8 0 0 1-5-1.38l-.36-.21-3.78.99 1.01-3.69-.24-.38a9.77 9.77 0 0 1-1.5-5.15c0-5.43 4.42-9.85 9.87-9.85 2.63 0 5.1 1.02 6.95 2.89a9.79 9.79 0 0 1 2.88 6.96c0 5.43-4.42 9.85-9.82 9.85Zm5.4-7.35c-.3-.15-1.77-.87-2.05-.97-.28-.1-.48-.15-.68.15-.2.3-.78.97-.95 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.47-.89-.79-1.49-1.77-1.66-2.07-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.18.2-.3.3-.5.1-.2.05-.38-.02-.53-.08-.15-.68-1.64-.94-2.25-.25-.59-.5-.51-.68-.52h-.58c-.2 0-.53.08-.8.38-.28.3-1.06 1.04-1.06 2.54 0 1.5 1.09 2.95 1.24 3.15.15.2 2.14 3.27 5.18 4.58.72.31 1.28.49 1.72.62.72.23 1.38.2 1.9.12.58-.09 1.77-.72 2.02-1.42.25-.7.25-1.3.18-1.42-.08-.13-.28-.2-.58-.35Z" fill="currentColor"/></svg>' }; if (type === "email") return { tone: "email", badge: "Email", icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75A2.75 2.75 0 0 1 5.75 4h12.5A2.75 2.75 0 0 1 21 6.75v10.5A2.75 2.75 0 0 1 18.25 20H5.75A2.75 2.75 0 0 1 3 17.25V6.75Zm2.15-.75 6.36 5.42a.75.75 0 0 0 .98 0L18.85 6H5.15Zm13.85 1.24-5.54 4.72a2.25 2.25 0 0 1-2.92 0L5 7.24v10.01c0 .41.34.75.75.75h12.5c.41 0 .75-.34.75-.75V7.24Z" fill="currentColor"/></svg>' }; if (type === "phone") return { tone: "phone", badge: "Phone", icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.62 10.79a15.46 15.46 0 0 0 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.31.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1C10.61 21 3 13.39 3 4c0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.26.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2Z" fill="currentColor"/></svg>' }; if (type === "naver") return { tone: "naver", badge: "Naver", icon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 8.5V6.75A2.75 2.75 0 0 0 18.25 4H5.75A2.75 2.75 0 0 0 3 6.75V8.5a1.5 1.5 0 0 1 0 3v1.75a1.5 1.5 0 0 1 0 3v1.75A2.75 2.75 0 0 0 5.75 20.75h12.5A2.75 2.75 0 0 0 21 18V16.25a1.5 1.5 0 0 1 0-3V11.5a1.5 1.5 0 0 1 0-3Z" fill="currentColor"/><path d="M9 4.5v16" stroke="#fff" stroke-width="1.4" stroke-dasharray="2.2 2.2"/></svg>' }; return null; }
function renderActionLink(action, className) { const resolved = resolveAction(action); const targetAttr = resolved.target ? ` target="${resolved.target}" rel="${resolved.rel}"` : ""; const visual = getChannelVisual(action?.type); const toneClass = visual ? ` btn-channel btn-channel--${visual.tone}` : ""; const icon = visual ? `<span class="btn-icon" aria-hidden="true">${visual.icon}</span>` : ""; return `<a class="${className}${toneClass}" href="${escapeHtml(resolved.href)}"${targetAttr}>${icon}<span class="btn-label">${escapeHtml(resolved.label)}</span></a>`; }
function renderSectionHead(eyebrow, title, desc) { if (!eyebrow && !title && !desc) return ""; return `<div class="section-head">${eyebrow ? `<p class="section-eyebrow">${escapeHtml(eyebrow)}</p>` : ""}${title ? `<h2 class="section-title">${escapeHtml(title)}</h2>` : ""}${desc ? `<p class="section-desc">${escapeHtml(desc)}</p>` : ""}</div>`; }

function renderHero(copy) {
  const hero = copy.hero || {};
  const heroImages = normalizeHeroImages(siteConfig.media.heroImages);
  const slides = hero.carouselSlides || [];
  return `<section class="section reveal"><div class="section-shell hero-shell"><div class="hero-grid hero-grid-carousel"><div class="hero-copy"><span class="hero-kicker">${escapeHtml(hero.kicker)}</span><h1 class="hero-title">${escapeHtmlWithBreaks(hero.title)}</h1>${hero.subtitle ? `<p class="hero-subtitle">${escapeHtml(hero.subtitle)}</p>` : ""}${(hero.chips || []).length ? `<div class="hero-chip-row">${(hero.chips || []).map((chip) => `<span class="hero-chip">${escapeHtml(chip)}</span>`).join("")}</div>` : ""}<div class="hero-cta">${renderActionLink(hero.primaryAction, "btn btn-primary")}${renderActionLink(hero.secondaryAction, "btn btn-secondary")}${renderActionLink(hero.tertiaryAction, "btn btn-ghost")}</div>${(hero.notes || []).length ? `<div class="hero-aside-note">${(hero.notes || []).map((note) => `<span>${escapeHtml(note)}</span>`).join("")}</div>` : ""}</div><div class="hero-carousel-card"><div class="hero-carousel-frame">${heroImages.map((src, index) => { const slide = slides[index] || {}; const title = slide.title || getBrandTitle(); const badge = slide.badge || ""; return `<div class="hero-slide${index === 0 ? " active" : ""}" data-hero-slide="${index}"><img src="${escapeHtml(src)}" alt="${escapeHtml(title)}"><div class="hero-slide-copy">${badge ? `<span class="hero-slide-badge">${escapeHtml(badge)}</span>` : ""}<strong>${escapeHtml(title)}</strong></div></div>`; }).join("")}</div><div class="hero-carousel-dots" role="tablist">${heroImages.map((_, index) => `<button type="button" class="hero-dot${index === 0 ? " active" : ""}" data-hero-dot="${index}" aria-label="Hero slide ${index + 1}"></button>`).join("")}</div></div></div></div></section>`;
}

function renderQuickFacts(copy) { if (!copy.quickFacts) return ""; return `<section id="quick-facts" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.quickFacts.eyebrow, copy.quickFacts.title, copy.quickFacts.desc)}<div class="summary-strip">${copy.quickFacts.items.map((item) => `<article class="summary-item"><span class="summary-label">${escapeHtml(item.label)}</span><strong class="summary-value">${escapeHtml(item.value)}</strong>${item.note ? `<span class="summary-note">${escapeHtml(item.note)}</span>` : ""}</article>`).join("")}</div></div></section>`; }
const TRUST_ICONS = {
  manager: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2Z"/><circle cx="12" cy="9.5" r="1.75"/><path d="M8.5 14c.6-1.5 1.9-2.25 3.5-2.25s2.9.75 3.5 2.25"/></svg>',
  privacy: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/></svg>',
  reply: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2Z"/></svg>',
};
function renderTrustStrip(copy) { if (!copy.trustStrip || !(copy.trustStrip.items || []).length) return ""; return `<section class="section reveal"><div class="section-shell"><div class="trust-strip">${copy.trustStrip.items.map((item) => `<div class="trust-item"><div class="trust-icon">${TRUST_ICONS[item.icon] || TRUST_ICONS.privacy}</div><div class="trust-copy"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.desc)}</p></div></div>`).join("")}</div></div></section>`; }
function renderConcept(copy) { if (!copy.concept) return ""; return `<section id="about" class="section reveal"><div class="section-shell">${renderSectionHead(copy.concept.eyebrow, copy.concept.title, copy.concept.desc)}<div class="concept-grid">${copy.concept.cards.map((card) => `<article class="concept-card"><h3>${escapeHtml(card.title)}</h3><p>${escapeHtml(card.copy)}</p></article>`).join("")}</div></div></section>`; }
function renderCollections(copy) { return `<section id="room-collections" class="section reveal"><div class="section-shell">${renderSectionHead(copy.collections.eyebrow, copy.collections.title, copy.collections.desc)}<div class="collection-grid">${(siteConfig.collections || []).map((collection) => { const title = currentLang === "ko" ? collection.titleKo : collection.titleEn; const stat = currentLang === "ko" ? collection.statKo : collection.statEn; const body = currentLang === "ko" ? collection.copyKo : collection.copyEn; const prefix = currentLang === "ko" ? "해당 호실" : "Rooms"; return `<article class="collection-card"><div class="collection-media"><img src="${escapeHtml(collection.image)}" alt="${escapeHtml(title)}"><span class="collection-stat">${escapeHtml(stat)}</span></div><div class="collection-body"><h3>${escapeHtml(title)}</h3><p class="collection-copy">${escapeHtml(body)}</p><ul class="collection-room-list"><li>${escapeHtml(`${prefix}: ${collection.rooms.join(" / ")}`)}</li></ul></div></article>`; }).join("")}</div></div></section>`; }
function renderInventory(copy) { return `<section class="section reveal"><div class="section-shell">${renderSectionHead(copy.inventory.eyebrow, copy.inventory.title, copy.inventory.desc)}<div class="inventory-toolbar"><p class="helper-copy">${escapeHtml(copy.inventory.helper)}</p><div class="filter-bar" role="tablist">${copy.inventory.filters.map((filter) => `<button type="button" class="filter-btn${activeRoomFilter === filter.id ? " active" : ""}" data-room-filter="${escapeHtml(filter.id)}">${escapeHtml(filter.label)}</button>`).join("")}</div></div><div class="room-grid">${(siteConfig.rooms || []).map((room) => { const hidden = activeRoomFilter !== "all" && !(room.filters || []).includes(activeRoomFilter); const tag = currentLang === "ko" ? room.tagKo : room.tagEn; const title = currentLang === "ko" ? room.titleKo : room.titleEn; const body = currentLang === "ko" ? room.copyKo : room.copyEn; const points = currentLang === "ko" ? room.pointsKo : room.pointsEn; const price = currentLang === "ko" ? room.priceKo : room.priceEn; return `<article class="room-card${hidden ? " is-hidden" : ""}"><div class="room-card-media"><img src="${escapeHtml(room.image)}" alt="${escapeHtml(title)}"></div><div class="room-card-body"><div class="room-card-top"><div class="room-card-title-wrap"><span class="room-card-tag">${escapeHtml(tag)}</span><h3 class="room-card-title">${escapeHtml(title)}</h3></div><span class="tier-pill">${escapeHtml(room.tier)}</span></div><p class="room-card-copy">${escapeHtml(body)}</p><div class="price-block"><p class="price-main">${escapeHtml(price)}</p></div><ul class="room-feature-list">${(points || []).map((point) => `<li>${escapeHtml(point)}</li>`).join("")}</ul><div class="room-card-actions">${renderActionLink({ href: "#contact", label: copy.inventory.primaryCta }, "btn btn-primary btn-compact")}${renderActionLink({ href: "#pricing", label: copy.inventory.secondaryCta }, "btn btn-secondary btn-compact")}</div></div></article>`; }).join("")}</div></div></section>`; }
function renderGallery(copy) { return `<section id="gallery" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.gallery.eyebrow, copy.gallery.title, copy.gallery.desc)}<div class="tier-gallery-grid">${(siteConfig.media.tierGallery || []).map((group) => { const title = currentLang === "ko" ? group.titleKo : group.titleEn; const badge = currentLang === "ko" ? group.badgeKo : group.badgeEn; const price = currentLang === "ko" ? group.priceKo : group.priceEn; const body = currentLang === "ko" ? group.descKo : group.descEn; return `<article class="tier-gallery-card"><div class="tier-gallery-head"><div>${badge ? `<span class="tier-gallery-badge">${escapeHtml(badge)}</span>` : ""}<h3>${escapeHtml(title)}</h3></div><strong class="tier-gallery-price">${escapeHtml(price)}</strong></div>${body ? `<p class="tier-gallery-copy">${escapeHtml(body)}</p>` : ""}<div class="tier-gallery-images">${(group.images || []).map((image) => { const caption = currentLang === "ko" ? image.captionKo : image.captionEn; return `<button type="button" class="gallery-item tier-gallery-item" data-gallery-src="${escapeHtml(image.src)}" data-gallery-alt="${escapeHtml(caption)}" data-gallery-caption="${escapeHtml(caption)}"><img src="${escapeHtml(image.src)}" alt="${escapeHtml(caption)}"><span class="visual-caption">${escapeHtml(caption)}</span></button>`; }).join("")}</div></article>`; }).join("")}</div></div></section>`; }
const INCLUDED_ICONS = {
  bathroom: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M5 12h14"/><path d="M7 12V7a2 2 0 0 1 4 0v5"/><path d="M6 12v3a4 4 0 0 0 4 4h4a4 4 0 0 0 4-4v-3"/></svg>',
  microwave: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><rect x="4" y="6" width="16" height="12" rx="2"/><path d="M8 10h5"/><path d="M8 13h5"/><path d="M17 10v4"/></svg>',
  laundry: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><rect x="5" y="4" width="14" height="16" rx="2"/><path d="M8 8h8"/><circle cx="12" cy="14" r="3.2"/></svg>',
  bed: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 12h16v6H4z"/><path d="M4 18v2"/><path d="M20 18v2"/><path d="M7 12V8h4a3 3 0 0 1 3 3v1"/></svg>',
};
function renderIncluded(copy) { return `<section id="included" class="section reveal"><div class="section-shell">${renderSectionHead(copy.included.eyebrow, copy.included.title, copy.included.desc)}<div class="included-grid simple-included-grid">${copy.included.cards.map((card) => `<article class="amenity-card simple-amenity-card">${card.icon && INCLUDED_ICONS[card.icon] ? `<span class="amenity-icon">${INCLUDED_ICONS[card.icon]}</span>` : ""}<h3 class="amenity-title">${escapeHtml(card.title)}</h3><p class="amenity-desc">${escapeHtml(card.desc)}</p></article>`).join("")}</div></div></section>`; }
function renderPricing(copy) { return `<section id="pricing" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.pricing.eyebrow, copy.pricing.title, copy.pricing.desc)}<div class="pricing-layout"><div class="pricing-panel"><div class="pricing-simple-grid">${copy.pricing.rows.map((row) => `<article class="pricing-row simple-pricing-row"><div class="pricing-row-head"><strong>${escapeHtml(row.tier)}</strong><span class="price-label">${escapeHtml(row.rooms)}</span></div><div class="pricing-row-body"><div class="pricing-allin-grid"><div class="pricing-col"><span class="pricing-col-label">${escapeHtml(currentLang === "ko" ? "월 비용" : "Monthly price")}</span><span class="pricing-col-value">${escapeHtml(row.price)}</span></div><div class="pricing-col"><span class="pricing-col-label">${escapeHtml(currentLang === "ko" ? "보증금" : "Deposit")}</span><span class="pricing-col-value">${escapeHtml(row.deposit)}</span></div></div><span class="helper-copy">${escapeHtml(row.note)}</span></div></article>`).join("")}</div></div><aside class="pricing-note-card"><h3>${escapeHtml(copy.pricing.sideTitle)}</h3><p>${escapeHtml(copy.pricing.sideBody)}</p><ul class="pricing-note-list">${copy.pricing.notes.map((note) => `<li>${escapeHtml(note)}</li>`).join("")}</ul></aside></div></div></section>`; }
function renderProcess(copy) { if (!copy.process) return ""; return `<section id="move-in" class="section reveal"><div class="section-shell">${renderSectionHead(copy.process.eyebrow, copy.process.title, copy.process.desc)}<div class="process-grid">${copy.process.steps.map((step, index) => `<article class="step-card"><span class="step-index">${index + 1}</span><h3>${escapeHtml(step.title)}</h3><p class="step-copy">${escapeHtml(step.copy)}</p></article>`).join("")}</div></div></section>`; }
function renderLocation(copy) { return `<section id="location" class="section reveal"><div class="section-shell">${renderSectionHead(copy.location.eyebrow, copy.location.title, copy.location.desc)}<div class="location-grid"><div class="map-card"><iframe class="map-frame" title="${escapeHtml(currentLang === "ko" ? "홈스테이드 서울 위치" : "Homestead Seoul location")}" src="${escapeHtml(siteConfig.contact.mapEmbed)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div><aside class="location-card">${copy.location.sideTitle ? `<h3>${escapeHtml(copy.location.sideTitle)}</h3>` : ""}${copy.location.sideBody ? `<p>${escapeHtml(copy.location.sideBody)}</p>` : ""}<ul class="location-list">${copy.location.points.map((point) => `<li>${escapeHtml(point)}</li>`).join("")}</ul></aside></div></div></section>`; }
function renderFaq(copy) { return `<section id="faq" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.faq.eyebrow, copy.faq.title, "")}<div class="faq-list">${copy.faq.items.map((item) => `<details class="faq-item"><summary>${escapeHtml(item.q)}</summary><p>${escapeHtml(item.a)}</p></details>`).join("")}</div></div></section>`; }
function renderStars(rating) { const n = Math.max(0, Math.min(5, Math.round(rating || 0))); return `<span class="testimonial-stars" aria-hidden="true">${"★".repeat(n)}${"☆".repeat(5 - n)}</span>`; }
function renderTestimonials(copy) { if (!copy.testimonials) return ""; return `<section id="testimonials" class="section reveal"><div class="section-shell">${renderSectionHead(copy.testimonials.eyebrow, copy.testimonials.title, "")}<div class="testimonial-grid">${copy.testimonials.items.map((item) => `<article class="testimonial-card">${renderStars(item.rating)}<p class="testimonial-quote">${escapeHtml(item.quote)}</p><div class="testimonial-meta"><strong>${escapeHtml(item.name)}</strong>${item.location ? `<span>${escapeHtml(item.location)}</span>` : ""}</div></article>`).join("")}</div></div></section>`; }
function renderContact(copy) { const channelCard = (channel) => { const action = resolveAction({ type: channel.type, label: channel.label, fallbackLabel: channel.label }); const attrs = action.target ? ` target="${action.target}" rel="${action.rel}"` : ""; const visual = getChannelVisual(channel.type); const toneClass = visual ? ` channel-card--${visual.tone}` : ""; const icon = visual ? `<span class="channel-icon channel-card-icon" aria-hidden="true">${visual.icon}</span>` : ""; const badge = visual?.badge || channel.type; return `<a class="channel-card${toneClass}" href="${escapeHtml(action.href)}"${attrs}><div class="channel-card-top">${icon}<div class="channel-card-main"><div class="channel-title"><strong>${escapeHtml(channel.label)}</strong><span class="channel-badge">${escapeHtml(badge)}</span></div>${channel.hint ? `<p class="channel-hint">${escapeHtml(channel.hint)}</p>` : ""}</div></div><span class="channel-action">${escapeHtml(currentLang === "ko" ? "바로 열기" : "Open")}</span></a>`; }; const responseBadge = copy.contact.responseNote ? `<span class="response-badge"><span class="pulse"></span>${escapeHtml(copy.contact.responseNote)}</span>` : ""; return `<section id="contact" class="section reveal"><div class="section-shell"><div class="contact-wrap contact-wrap--channels"><div class="contact-intro">${renderSectionHead(copy.contact.eyebrow, copy.contact.title, copy.contact.message)}${responseBadge}</div><div class="channel-grid">${copy.contact.channels.map(channelCard).join("")}</div></div></div></section>`; }

function renderPage() { const copy = getCurrentCopy(); const sections = { hero: renderHero(copy), trustStrip: renderTrustStrip(copy), quickFacts: renderQuickFacts(copy), concept: renderConcept(copy), collections: renderCollections(copy), inventory: renderInventory(copy), gallery: renderGallery(copy), included: renderIncluded(copy), pricing: renderPricing(copy), process: renderProcess(copy), testimonials: renderTestimonials(copy), location: renderLocation(copy), faq: renderFaq(copy), contact: renderContact(copy) }; document.getElementById("app").innerHTML = (copy.sections || []).map((key) => sections[key] || "").join(""); renderChrome(copy); bindInventoryFilters(); bindGalleryModal(); bindInquiryForm(); bindReveal(); bindDrawerLinks(); bindHeroCarousel(); applySeo(copy); }
function renderChrome(copy) { document.documentElement.lang = currentLang; document.getElementById("brandTitle").textContent = getBrandTitle(); document.getElementById("brandSubtitle").textContent = getBrandSubtitle(); document.getElementById("brandSince").textContent = getBrandTrustLine(); document.getElementById("drawerTagline").textContent = getBrandSubtitle(); document.getElementById("drawerSince").textContent = getBrandTrustLine(); document.getElementById("footerBrand").textContent = getBrandTitle(); const footerCopy = document.getElementById("footerCopy"); const footerAddress = document.getElementById("footerAddress"); const footerSep = document.querySelector(".footer-sep"); footerCopy.textContent = copy.footer.copy || ""; footerCopy.hidden = !copy.footer.copy; footerAddress.textContent = copy.footer.address || ""; footerAddress.hidden = !copy.footer.address; if (footerSep) footerSep.hidden = !copy.footer.address; document.getElementById("desktopNav").innerHTML = copy.nav.map((item) => `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join(""); document.getElementById("mobileNav").innerHTML = copy.nav.map((item) => `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join(""); const hero = copy.hero || {}; const headerPrimary = resolveAction(hero.primaryAction); const headerCta = document.getElementById("headerPrimaryCta"); headerCta.textContent = headerPrimary.label; headerCta.href = headerPrimary.href; if (headerPrimary.target) { headerCta.target = headerPrimary.target; headerCta.rel = headerPrimary.rel; } else { headerCta.removeAttribute("target"); headerCta.removeAttribute("rel"); } document.getElementById("drawerCtas").innerHTML = renderActionLink(hero.primaryAction, "btn btn-primary") + renderActionLink(hero.secondaryAction, "btn btn-secondary"); document.getElementById("stickyMobileCta").innerHTML = `<div class="sticky-mobile-cta-inner">${copy.contact.mobileCtas.map((cta, index) => renderActionLink(cta, `btn ${index === 0 ? "btn-primary" : "btn-secondary"}`)).join("")}</div>`; document.getElementById("footerLinks").innerHTML = copy.footer.links.map((item) => `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join(""); document.querySelectorAll("[data-lang-btn]").forEach((button) => button.classList.toggle("active", button.dataset.langBtn === currentLang)); }
function formatInternationalPhone(phone) {
  const digits = normalizePhoneToDigits(phone);
  if (!digits) return "";
  if (digits.startsWith("82")) return `+${digits}`;
  if (digits.startsWith("0")) return `+82${digits.slice(1)}`;
  return `+${digits}`;
}
function applyStructuredData(copy) {
  const lodgingSchemaNode = document.getElementById("lodgingSchema");
  const faqSchemaNode = document.getElementById("faqSchema");
  if (!lodgingSchemaNode && !faqSchemaNode) return;

  const siteUrl = `${location.protocol}//${location.host}`;
  const whatsappDigits = normalizePhoneToDigits(siteConfig.contact?.whatsappNumber || siteConfig.contact?.phone);
  const contactPhone = formatInternationalPhone(siteConfig.contact?.phone || "");
  const faqItems = (copy?.faq?.items || []).filter((item) => item && item.q && item.a);

  if (lodgingSchemaNode) {
    const lodgingSchema = {
      "@context": "https://schema.org",
      "@type": "LodgingBusiness",
      name: "Homestead Seoul",
      alternateName: "홈스테이드 서울",
      description:
        "Affordable private guesthouse in Bangbae-dong, Seoul. Private rooms with bathroom, AC, desk, and laundry support.",
      url: siteUrl,
      address: {
        "@type": "PostalAddress",
        streetAddress: "방배동 911-14",
        addressLocality: "서초구",
        addressRegion: "서울특별시",
        addressCountry: "KR",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: 37.4836,
        longitude: 126.9973,
      },
      priceRange: "₩₩",
      amenityFeature: [
        { "@type": "LocationFeatureSpecification", name: "Private Bathroom", value: true },
        { "@type": "LocationFeatureSpecification", name: "Air Conditioning", value: true },
        { "@type": "LocationFeatureSpecification", name: "Washing Machine", value: true },
        { "@type": "LocationFeatureSpecification", name: "Work Desk", value: true },
      ],
      availableLanguage: ["Korean", "English"],
      telephone: contactPhone,
      checkinTime: "15:00",
      checkoutTime: "11:00",
      sameAs: [
        isUsableUrl(siteConfig.contact?.kakaoUrl) ? siteConfig.contact.kakaoUrl.trim() : "",
        whatsappDigits ? `https://wa.me/${whatsappDigits}` : "",
      ].filter(Boolean),
    };
    const testimonialItems = (copy?.testimonials?.items || []).filter((item) => item && item.quote);
    if (testimonialItems.length) {
      lodgingSchema.aggregateRating = {
        "@type": "AggregateRating",
        ratingValue: (testimonialItems.reduce((sum, item) => sum + (item.rating || 5), 0) / testimonialItems.length).toFixed(1),
        reviewCount: testimonialItems.length,
      };
      lodgingSchema.review = testimonialItems.map((item) => ({
        "@type": "Review",
        author: { "@type": "Person", name: item.name || "Guest" },
        reviewRating: { "@type": "Rating", ratingValue: item.rating || 5, bestRating: 5 },
        reviewBody: item.quote,
      }));
    }
    lodgingSchemaNode.textContent = JSON.stringify(lodgingSchema);
  }

  if (faqSchemaNode) {
    const faqSchema = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      inLanguage: currentLang === "ko" ? "ko-KR" : "en",
      mainEntity: faqItems.map((item) => ({
        "@type": "Question",
        name: String(item.q).replace(/^Q\.\s*/i, "").trim(),
        acceptedAnswer: {
          "@type": "Answer",
          text: String(item.a).replace(/^A\.\s*/i, "").trim(),
        },
      })),
    };
    faqSchemaNode.textContent = JSON.stringify(faqSchema);
  }
}
function applySeo(copy) {
  document.title = copy.seo.title;
  document.getElementById("metaDescription").setAttribute("content", copy.seo.description);
  document.getElementById("ogTitle").setAttribute("content", copy.seo.ogTitle);
  document.getElementById("ogDescription").setAttribute("content", copy.seo.ogDescription);
  document.querySelector('meta[property="og:locale"]').setAttribute("content", copy.seo.locale);
  applyStructuredData(copy);
}
function bindInventoryFilters() { document.querySelectorAll("[data-room-filter]").forEach((button) => button.addEventListener("click", () => { activeRoomFilter = button.dataset.roomFilter || "all"; renderPage(); })); }
function openImageModal(src, alt, caption) { const modal = document.getElementById("imageModal"); document.getElementById("imageModalImg").src = src; document.getElementById("imageModalImg").alt = alt; document.getElementById("imageModalCaption").textContent = caption; modal.hidden = false; document.body.style.overflow = "hidden"; }
function closeImageModal() { const modal = document.getElementById("imageModal"); document.getElementById("imageModalImg").src = ""; document.getElementById("imageModalCaption").textContent = ""; modal.hidden = true; document.body.style.overflow = ""; }
function bindGalleryModal() { document.querySelectorAll("[data-gallery-src]").forEach((button) => button.addEventListener("click", () => openImageModal(button.dataset.gallerySrc || "", button.dataset.galleryAlt || "", button.dataset.galleryCaption || ""))); }
function stopHeroCarousel() { if (heroCarouselTimer) { clearInterval(heroCarouselTimer); heroCarouselTimer = null; } }
function setHeroSlide(index) { const slides = Array.from(document.querySelectorAll("[data-hero-slide]")); const dots = Array.from(document.querySelectorAll("[data-hero-dot]")); if (slides.length === 0) return; heroSlideIndex = index % slides.length; slides.forEach((slide, slideIndex) => slide.classList.toggle("active", slideIndex === heroSlideIndex)); dots.forEach((dot, dotIndex) => dot.classList.toggle("active", dotIndex === heroSlideIndex)); }
function bindHeroCarousel() { stopHeroCarousel(); const slides = Array.from(document.querySelectorAll("[data-hero-slide]")); const dots = Array.from(document.querySelectorAll("[data-hero-dot]")); if (slides.length === 0) return; heroSlideIndex = 0; setHeroSlide(0); dots.forEach((dot) => dot.addEventListener("click", () => setHeroSlide(Number(dot.dataset.heroDot || "0")))); if (slides.length < 2) return; heroCarouselTimer = window.setInterval(() => setHeroSlide(heroSlideIndex + 1), 5200); }
function setStatus(message, type = "") { const node = document.getElementById("formStatus"); if (!node) return; node.textContent = message; node.className = type ? `form-status ${type}` : "form-status"; }
function getInquiryApiUrl() { return location.hostname.endsWith("github.io") ? "https://homesteadseoul.com/api/inquiry" : "/api/inquiry"; }
function shouldOpenDraftInsteadOfSending() { return false; }
function triggerInquiryFallback(payload, overrideMessage = "") { const message = overrideMessage || (payload.language === "ko" ? "문의 전송에 실패했습니다. 잠시 후 다시 시도하거나 카카오톡, 전화, 이메일로 문의해주세요." : "We could not send your inquiry. Please try again shortly or contact us by WhatsApp, phone, or email."); setStatus(message, "error"); }
function formatInquiryErrorMessage(payload, result, responseText) {
  if (result && typeof result.message === "string" && result.message.trim()) {
    if (typeof result.detail === "string" && result.detail.trim()) return `${result.message} (${result.detail.trim()})`;
    return result.message.trim();
  }
  if (/just a moment/i.test(responseText || "")) {
    return payload.language === "ko" ? "사이트 보안 설정 때문에 문의 요청이 차단되었습니다. 잠시 후 다시 시도하거나 다른 문의 채널을 이용해주세요." : "Your inquiry request was blocked by the site's security settings. Please try again shortly or use another contact method.";
  }
  return payload.language === "ko" ? "문의 전송에 실패했습니다. 잠시 후 다시 시도해주세요." : "We could not send your inquiry. Please try again shortly.";
}
async function handleInquirySubmit(event) { event.preventDefault(); const copy = getCurrentCopy(); const form = event.currentTarget; const data = new FormData(form); const payload = { name: String(data.get("name") || "").trim(), contact: String(data.get("contact") || "").trim(), message: String(data.get("message") || "").trim(), language: String(data.get("language") || currentLang), turnstileToken: String(data.get("turnstileToken") || "").trim() }; if (shouldOpenDraftInsteadOfSending()) { triggerInquiryFallback(payload); return; } setStatus(copy.contact.form.sending); try { const response = await fetch(getInquiryApiUrl(), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const contentType = response.headers.get("content-type") || ""; const responseText = await response.text(); let result = null; if (contentType.includes("application/json")) { try { result = responseText ? JSON.parse(responseText) : null; } catch (_) { result = null; } } if (response.ok && result && result.ok) { form.reset(); setStatus(copy.contact.form.success, "success"); return; } if (result || responseText) { const message = formatInquiryErrorMessage(payload, result, responseText); console.error("Inquiry API error", { status: response.status, result, responseText }); setStatus(message, "error"); return; } if (response.status === 404 || response.status >= 500) { triggerInquiryFallback(payload); return; } setStatus(copy.contact.form.error, "error"); } catch (error) { console.error("Inquiry request failed", error); triggerInquiryFallback(payload); } }
function bindInquiryForm() {}
function bindReveal() { const elements = document.querySelectorAll(".reveal"); const observer = new IntersectionObserver((entries) => { entries.forEach((entry) => { if (!entry.isIntersecting) return; entry.target.classList.add("show"); observer.unobserve(entry.target); }); }, { threshold: 0.14 }); elements.forEach((element) => observer.observe(element)); }
function openDrawer() { const drawer = document.getElementById("mobileDrawer"); const backdrop = document.getElementById("drawerBackdrop"); const menuBtn = document.getElementById("menuBtn"); lastFocusedElement = document.activeElement; drawer.classList.add("open"); drawer.setAttribute("aria-hidden", "false"); backdrop.hidden = false; menuBtn.setAttribute("aria-expanded", "true"); isDrawerOpen = true; }
function closeDrawer() { const drawer = document.getElementById("mobileDrawer"); const backdrop = document.getElementById("drawerBackdrop"); const menuBtn = document.getElementById("menuBtn"); drawer.classList.remove("open"); drawer.setAttribute("aria-hidden", "true"); backdrop.hidden = true; menuBtn.setAttribute("aria-expanded", "false"); isDrawerOpen = false; if (lastFocusedElement instanceof HTMLElement) lastFocusedElement.focus(); }
function bindDrawerLinks() { document.querySelectorAll("#mobileDrawer a").forEach((link) => link.addEventListener("click", closeDrawer)); }
function bindStaticChrome() { document.querySelectorAll("[data-lang-btn]").forEach((button) => button.addEventListener("click", () => { if (button.dataset.langBtn === currentLang) return; currentLang = button.dataset.langBtn; activeRoomFilter = "all"; localStorage.setItem("preferred_lang", currentLang); closeDrawer(); renderPage(); window.scrollTo({ top: 0, behavior: "smooth" }); })); document.getElementById("menuBtn").addEventListener("click", () => (isDrawerOpen ? closeDrawer() : openDrawer())); document.getElementById("drawerCloseBtn").addEventListener("click", closeDrawer); document.getElementById("drawerBackdrop").addEventListener("click", closeDrawer); document.getElementById("imageModalClose").addEventListener("click", closeImageModal); document.getElementById("imageModal").addEventListener("click", (event) => { if (event.target === document.getElementById("imageModal")) closeImageModal(); }); document.addEventListener("keydown", (event) => { if (event.key !== "Escape") return; if (!document.getElementById("imageModal").hidden) { closeImageModal(); return; } if (isDrawerOpen) closeDrawer(); }); }
function bindYear() { document.getElementById("year").textContent = String(new Date().getFullYear()); }
function loadLocalAdminOverrides() { try { const raw = localStorage.getItem(ADMIN_OVERRIDE_KEY); if (!raw) return; siteConfig = deepMerge(siteConfig, JSON.parse(raw)); } catch (_) {} }
async function loadServerAdminOverrides() { try { const response = await fetch("/api/site-config", { cache: "no-store" }); if (!response.ok) return false; const result = await response.json(); if (!result || !result.ok || !result.config || typeof result.config !== "object") return false; siteConfig = deepMerge(siteConfig, result.config); return true; } catch (_) { return false; } }

async function init() { applyContentRevision(siteConfig); const serverLoaded = await loadServerAdminOverrides(); if (!serverLoaded) loadLocalAdminOverrides(); applyContentRevision(siteConfig); if (siteConfig.pages?.ko?.hero) siteConfig.pages.ko.hero.notes = sanitizeHeroNotes(siteConfig.pages.ko.hero.notes); if (siteConfig.pages?.en?.hero) siteConfig.pages.en.hero.notes = sanitizeHeroNotes(siteConfig.pages.en.hero.notes); bindStaticChrome(); bindYear(); renderPage(); }
init();
