(function () {
  const ADMIN_OVERRIDE_KEY = "homestead_admin_overrides";
  const ROOM_IMAGES = {
    heroS: "images/room-s-1.jpg",
    heroA: "images/room-a-1.jpg",
    heroB: "images/room-b-1.jpg",
    s1: "images/room-s-1.jpg",
    s2: "images/room-s-2.jpg",
    a1: "images/room-a-1.jpg",
    a2: "images/room-a-2.jpg",
    b1: "images/room-b-1.jpg",
    b2: "images/room-b-2.jpg",
  };

  const DEFAULT_CONFIG = {
    branding: {
      ko: "홈스테이드 서울",
      en: "Homestead Seoul",
      subtitleKo: "서울의 1인 전용 프라이빗룸",
      subtitleEn: "Private Room Urban Living",
      trustKo: "Since 2007",
      trustEn: "Since 2007",
    },
    contact: {
      phone: "010-3286-8682",
      email: "homesteadseoul@gmail.com",
      kakaoUrl: "https://open.kakao.com/o/s9L6lBli",
      whatsappNumber: "821032868682",
      naverUrl: "https://map.naver.com/p/entry/place/2069232581?placePath=%2Fticket%3Fentry%3Dpll%26from%3Dnx%26fromNxList%3Dtrue%26from%3Dmap%26fromPanelNum%3D1%26additionalHeight%3D76%26timestamp%3D202608260949%26locale%3Dko%26svcName%3Dmap_pcv5&placeSearchOption=entry%3Dpll%26fromNxList%3Dtrue&searchType=place&c=15.00,0,0,0,dh",
      mapEmbed:
        "https://www.google.com/maps?q=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EC%84%9C%EC%B4%88%EA%B5%AC%20%EB%B0%A9%EB%B0%B0%EB%8F%99%20911-14&output=embed",
    },
    media: {
      heroImages: [ROOM_IMAGES.heroS, ROOM_IMAGES.heroA, ROOM_IMAGES.heroB],
      tierGallery: [
        {
          tier: "S",
          titleKo: "S 타입",
          titleEn: "S type room",
          badgeKo: "",
          badgeEn: "",
          priceKo: "월 100만원",
          priceEn: "$32.99/day ($999/month)",
          descKo: "",
          descEn: "",
          images: [
            { src: ROOM_IMAGES.s1, captionKo: "밝고 여유 있는 S 타입 객실", captionEn: "Bright and spacious S type room" },
            { src: ROOM_IMAGES.s2, captionKo: "창이 있는 S 타입 욕실", captionEn: "Windowed bathroom in an S type room" },
          ],
        },
        {
          tier: "A",
          titleKo: "A 타입",
          titleEn: "A type room",
          badgeKo: "",
          badgeEn: "",
          priceKo: "월 80만원",
          priceEn: "$26.99/day ($799/month)",
          descKo: "",
          descEn: "",
          images: [
            { src: ROOM_IMAGES.a1, captionKo: "균형감 있는 A 타입 객실", captionEn: "Balanced A type room" },
            { src: ROOM_IMAGES.a2, captionKo: "정돈감 있는 A 타입 객실", captionEn: "Clean and practical A type room" },
          ],
        },
        {
          tier: "B",
          titleKo: "B 타입",
          titleEn: "B type room",
          badgeKo: "",
          badgeEn: "",
          priceKo: "월 60만원부터",
          priceEn: "$19.99/day ($599/month)",
          descKo: "",
          descEn: "",
          images: [
            { src: ROOM_IMAGES.b1, captionKo: "밝은 톤의 B 타입 객실", captionEn: "Bright B type room" },
            { src: ROOM_IMAGES.b2, captionKo: "기본 구성이 갖춰진 B 타입 객실", captionEn: "B type room with essential furnishings" },
          ],
        },
      ],
    },
    rooms: [
      {
        id: "201",
        tier: "S",
        image: ROOM_IMAGES.s1,
        tagKo: "시그니처 정숙",
        tagEn: "Signature quiet",
        titleKo: "201호",
        titleEn: "Room 201",
        copyKo: "크고 좌우 인접실이 없어 가장 조용한 축의 대표 객실입니다.",
        copyEn: "A large room in the quietest line, with no rooms directly on either side.",
        pointsKo: ["대형 타입", "욕실 창", "정숙 선호"],
        pointsEn: ["Large room", "Bathroom window", "Low-noise placement"],
        filters: ["quiet", "window", "spacious"],
        priceKo: "월 100만원",
        priceEn: "KRW 1,000,000 / month",
      },
      {
        id: "301",
        tier: "S",
        image: ROOM_IMAGES.s1,
        tagKo: "시그니처 정숙",
        tagEn: "Signature quiet",
        titleKo: "301호",
        titleEn: "Room 301",
        copyKo: "201호와 같은 조용한 라인의 상층 객실입니다.",
        copyEn: "An upper-floor room in the same quiet signature line as Room 201.",
        pointsKo: ["대형 타입", "욕실 창", "상층 선호"],
        pointsEn: ["Large room", "Bathroom window", "Higher floor"],
        filters: ["quiet", "window", "spacious"],
        priceKo: "월 100만원",
        priceEn: "KRW 1,000,000 / month",
      },
      {
        id: "401",
        tier: "S",
        image: ROOM_IMAGES.s1,
        tagKo: "시그니처 정숙",
        tagEn: "Signature quiet",
        titleKo: "401호",
        titleEn: "Room 401",
        copyKo: "고층의 조용한 S 타입을 찾는 분에게 적합합니다.",
        copyEn: "A higher-floor S-tier room for guests who want a quieter placement.",
        pointsKo: ["대형 타입", "욕실 창", "정숙 우선"],
        pointsEn: ["Large room", "Bathroom window", "Quiet-first layout"],
        filters: ["quiet", "window", "spacious"],
        priceKo: "월 100만원",
        priceEn: "KRW 1,000,000 / month",
      },
      {
        id: "101",
        tier: "S",
        image: ROOM_IMAGES.s1,
        tagKo: "가장 큰 객실",
        tagEn: "Largest room",
        titleKo: "101호",
        titleEn: "Room 101",
        copyKo: "가장 넓은 객실이라 장기 거주 안정감이 큰 편입니다.",
        copyEn: "The largest room, with the most spacious long-stay feel.",
        pointsKo: ["가장 큰 타입", "여유 있는 동선", "장기 거주 적합"],
        pointsEn: ["Largest footprint", "More circulation", "Long-stay friendly"],
        filters: ["spacious"],
        priceKo: "월 100만원",
        priceEn: "KRW 1,000,000 / month",
      },
      {
        id: "102",
        tier: "S",
        image: ROOM_IMAGES.a2,
        tagKo: "직사각형 구조",
        tagEn: "Rectangular layout",
        titleKo: "102호",
        titleEn: "Room 102",
        copyKo: "직사각형이 잘 빠져 책상과 수납 배치가 쉬운 타입입니다.",
        copyEn: "A clean rectangular S-tier room that makes furniture placement easier.",
        pointsKo: ["직사각형 구조", "실용적인 배치", "정돈감"],
        pointsEn: ["Rectangular layout", "Easy setup", "Clean room shape"],
        filters: ["rectangle", "spacious"],
        priceKo: "월 100만원",
        priceEn: "KRW 1,000,000 / month",
      },
      {
        id: "205",
        tier: "A+",
        image: ROOM_IMAGES.a1,
        tagKo: "복도 끝 조용한 객실",
        tagEn: "Quiet end room",
        titleKo: "205호",
        titleEn: "Room 205",
        copyKo: "크고 복도 끝에 있어 비교적 조용한 A+ 타입입니다.",
        copyEn: "A larger A+ room near the end of the hallway for a quieter feel.",
        pointsKo: ["대형 타입", "복도 끝", "개별 견적"],
        pointsEn: ["Large room", "End-of-hall placement", "Quoted individually"],
        filters: ["quiet", "spacious"],
        priceKo: "A+ 개별 안내",
        priceEn: "Quoted individually",
      },
      {
        id: "212",
        tier: "A",
        image: ROOM_IMAGES.a1,
        tagKo: "채광 우수",
        tagEn: "Bright room",
        titleKo: "212호",
        titleEn: "Room 212",
        copyKo: "중간 크기지만 채광이 좋고 욕실 창이 있는 균형형 객실입니다.",
        copyEn: "A balanced mid-size room with good natural light and a bathroom window.",
        pointsKo: ["좋은 채광", "욕실 창", "균형형"],
        pointsEn: ["Good sunlight", "Bathroom window", "Balanced layout"],
        filters: ["window"],
        priceKo: "월 80만원",
        priceEn: "KRW 800,000 / month",
      },
      {
        id: "409",
        tier: "A",
        image: ROOM_IMAGES.a2,
        tagKo: "실용형 직사각형",
        tagEn: "Practical rectangle",
        titleKo: "409호",
        titleEn: "Room 409",
        copyKo: "넓고 직사각형이라 책상과 수납 동선 정리가 쉽습니다.",
        copyEn: "A spacious rectangular room that is easy to organize.",
        pointsKo: ["넓은 구조", "직사각형", "실용적"],
        pointsEn: ["Spacious shape", "Rectangular layout", "Practical use"],
        filters: ["rectangle", "spacious"],
        priceKo: "월 80만원",
        priceEn: "KRW 800,000 / month",
      },
      {
        id: "208",
        tier: "A",
        image: ROOM_IMAGES.a2,
        tagKo: "실용형 직사각형",
        tagEn: "Practical rectangle",
        titleKo: "208호",
        titleEn: "Room 208",
        copyKo: "정돈된 직사각형 구조를 선호하는 분에게 무난한 선택입니다.",
        copyEn: "A good fit if you prefer a straightforward rectangular room.",
        pointsKo: ["직사각형 구조", "무난한 동선", "A 타입"],
        pointsEn: ["Rectangular layout", "Simple circulation", "A-tier value"],
        filters: ["rectangle"],
        priceKo: "월 80만원",
        priceEn: "KRW 800,000 / month",
      },
      {
        id: "209",
        tier: "A",
        image: ROOM_IMAGES.a2,
        tagKo: "실용형 직사각형",
        tagEn: "Practical rectangle",
        titleKo: "209호",
        titleEn: "Room 209",
        copyKo: "가구 배치가 쉬워 생활 동선을 안정적으로 만들기 좋습니다.",
        copyEn: "Easy to set up for a stable daily routine and furniture layout.",
        pointsKo: ["직사각형 구조", "생활 동선 안정", "장기 거주 적합"],
        pointsEn: ["Rectangular layout", "Stable routine", "Good for longer stays"],
        filters: ["rectangle"],
        priceKo: "월 80만원",
        priceEn: "KRW 800,000 / month",
      },
      {
        id: "204",
        tier: "A",
        image: ROOM_IMAGES.a2,
        tagKo: "실용형 직사각형",
        tagEn: "Practical rectangle",
        titleKo: "204호",
        titleEn: "Room 204",
        copyKo: "깔끔하고 효율적인 구조를 원하는 분에게 잘 맞는 타입입니다.",
        copyEn: "A practical room for guests who want a clean and efficient shape.",
        pointsKo: ["정리감 좋은 구조", "합리적 선택", "A 타입"],
        pointsEn: ["Clean room shape", "Practical choice", "A tier"],
        filters: ["rectangle"],
        priceKo: "월 80만원",
        priceEn: "KRW 800,000 / month",
      },
    ],
    collections: [
      {
        image: ROOM_IMAGES.s1,
        titleKo: "시그니처 정숙 객실",
        titleEn: "Signature Quiet Rooms",
        statKo: "정숙 우선",
        statEn: "Quiet-first",
        copyKo: "201 / 301 / 401호는 좌우 인접실이 없어 조용함을 우선 보는 사용자에게 적합합니다.",
        copyEn: "Rooms 201, 301, and 401 sit in the quietest line, with no rooms directly on either side.",
        rooms: ["201", "301", "401"],
      },
      {
        image: ROOM_IMAGES.a1,
        titleKo: "실용형 직사각형 객실",
        titleEn: "Practical Rectangular Layouts",
        statKo: "배치가 쉬운 구조",
        statEn: "Easy to organize",
        copyKo: "102 / 204 / 208 / 209 / 409호는 책상과 수납 배치가 쉬운 실용형 구조입니다.",
        copyEn: "Rooms 102, 204, 208, 209, and 409 are shaped for practical furniture placement and easy daily routines.",
        rooms: ["102", "204", "208", "209", "409"],
      },
      {
        image: ROOM_IMAGES.s2,
        titleKo: "욕실 창이 있는 객실",
        titleEn: "Rooms with Windowed Bathrooms",
        statKo: "환기와 채광",
        statEn: "Light and ventilation",
        copyKo: "201 / 301 / 401 / 212호는 욕실 창이 있어 환기와 밝기를 중요하게 보는 분에게 적합합니다.",
        copyEn: "Rooms 201, 301, 401, and 212 include bathroom windows for better ventilation and a brighter feel.",
        rooms: ["201", "301", "401", "212"],
      },
    ],
    pages: {
      ko: {
        seo: {
          title: "홈스테이드 서울 | 서울 1인 전용 프라이빗룸",
          description: "방배역 인근 1인 전용 고시텔. 월 60만원부터, 1개월 보증금 기준, 관리비/공과금 없음.",
          ogTitle: "홈스테이드 서울 | 서울 1인 전용 프라이빗룸",
          ogDescription: "가격, 객실 차이, 위치, 문의 동선을 빠르게 비교할 수 있는 1인 전용 주거형 홈페이지.",
          locale: "ko_KR",
        },
        nav: [
          { href: "#quick-facts", label: "Quick Facts" },
          { href: "#gallery", label: "사진" },
          { href: "#included", label: "기본 구성" },
          { href: "#testimonials", label: "후기" },
          { href: "#location", label: "위치" },
          { href: "#faq", label: "FAQ" },
          { href: "#contact", label: "문의" },
        ],
        sections: ["hero", "trustStrip", "quickFacts", "gallery", "included", "testimonials", "location", "faq", "contact"],
        trustStrip: {
          items: [
            { icon: "manager", title: "1층 상주 매니저", desc: "체크인·체크아웃부터 건물 보안까지, 1층 상주 매니저가 직접 도와드립니다." },
            { icon: "privacy", title: "개인 욕실, 잠금 도어", desc: "모든 객실은 전용 욕실과 잠금장치가 있어 프라이버시가 보장됩니다." },
            { icon: "reply", title: "빠른 답변", desc: "카카오톡으로 언제든 문의하세요. 보통 1시간 이내 답변드립니다." },
          ],
        },
        hero: {
          kicker: "Bangbae Station · Private room · One person only",
          title: "방배역 도보 2분<br>혼자 쓰는 풀옵션",
          subtitle: "조용한 1인실 / 전용 욕실 / 관리비 없음 / 즉시 입실",
          chips: [],
          notes: [],
          primaryAction: { type: "kakao", label: "입실 문의", fallbackLabel: "입실 문의" },
          secondaryAction: { href: "#gallery", label: "사진 보기" },
          tertiaryAction: { type: "phone", label: "전화 문의" },
          carouselSlides: [
            { title: "밝고 정돈된 1인 전용 프라이빗룸" },
            { title: "혼자 지내기 편한 생활 동선" },
            { title: "서울 일상에 맞춘 차분한 공간" },
          ],
        },
        quickFacts: {
          eyebrow: "Quick Facts",
          title: "",
          desc: "",
          items: [
            { label: "월 비용", value: "60만원부터", note: "B 타입 기준" },
            { label: "보증금", value: "1달", note: "" },
            { label: "관리비", value: "없음", note: "" },
            { label: "공과금", value: "추가 없음", note: "" },
          ],
        },
        collections: {
          eyebrow: "Room Picks",
          title: "원하는 기준으로 먼저 객실을 좁혀보세요",
          desc: "조용한 방, 직사각형 구조, 욕실 창 같은 기준으로 먼저 비교하면 문의가 빨라집니다.",
        },
        inventory: {
          eyebrow: "Room List",
          title: "호실별 차이를 한눈에 비교",
          desc: "한국어 페이지는 가격과 호실 차이를 빠르게 보는 흐름이 중요하므로, 방별 특징을 먼저 배치합니다.",
          helper: "필터로 조용한 객실, 직사각형 구조, 욕실 창 있는 객실만 모아볼 수 있습니다.",
          filters: [
            { id: "all", label: "전체" },
            { id: "quiet", label: "조용한 객실" },
            { id: "spacious", label: "넓은 객실" },
            { id: "rectangle", label: "직사각형" },
            { id: "window", label: "욕실 창" },
          ],
          primaryCta: "이 객실 문의",
          secondaryCta: "가격 보기",
        },
        gallery: {
          eyebrow: "Photo Gallery",
          title: "객실 사진",
          desc: "",
        },
        included: {
          eyebrow: "Included",
          title: "필요한 건 대부분 이미 갖춰져 있어요",
          desc: "입주 당일부터 바로 생활할 수 있도록 기본을 채웠습니다.",
          cards: [
            { icon: "bathroom", title: "개인 욕실", desc: "모든 객실에 개인 욕실이 포함됩니다." },
            { icon: "laundry", title: "세탁기 + 냉장고 + 전자레인지", desc: "세탁기, 냉장고, 전자레인지까지 생활 가전을 모두 갖췄습니다." },
            { icon: "bed", title: "침대 + 침구 + 생활용품", desc: "침대, 침구, 수건, 비누 등 기본 생활용품이 준비됩니다." },
          ],
        },
        pricing: {
          eyebrow: "Pricing",
          title: "월 비용과 보증금 구조를 명확하게",
          desc: "한국어 페이지는 총액과 보증금이 먼저 보여야 비교가 쉽습니다.",
          rows: [
            { tier: "S 타입", rooms: "201 / 301 / 401 / 101 / 102", price: "월 100만원", deposit: "1개월분 기준", note: "조용함, 넓이, 선호도가 높은 객실" },
            { tier: "A 타입", rooms: "212 / 204 / 208 / 209 / 409", price: "월 80만원", deposit: "1개월분 기준", note: "실용적인 구조와 균형형 객실" },
            { tier: "B 타입", rooms: "가용 시 안내", price: "월 60만원부터", deposit: "1개월분 기준", note: "예산 우선 사용자를 위한 기본형" },
            { tier: "A+ 타입", rooms: "205", price: "개별 안내", deposit: "개별 안내", note: "복도 끝의 조용한 A+ 객실" },
          ],
          sideTitle: "운영 조건",
          sideBody: "한국어 페이지는 비교와 문의가 빨라야 하므로, 꼭 필요한 조건만 짧고 명확하게 보여줍니다.",
          notes: ["모든 객실은 1인 전용입니다.", "관리비/공과금은 별도로 받지 않습니다.", "보증금은 1개월분 기준입니다."],
        },
        testimonials: {
          eyebrow: "후기",
          title: "실제로 머물렀던 분들의 후기",
          items: [
            { name: "상헌", location: "", rating: 5, quote: "위치가 정말 좋고(지하철, 버스, 공원) 관리인분과 호스트 모두 매우 친절합니다." },
            { name: "Hyeran", location: "", rating: 5, quote: "방배역 3번출구 2분 거리로 안전하고, 1층 관리실에 관리아저씨도 계셔서 안심이 됩니다. 혼자 지내실 분들께 추천하는 방입니다!" },
            { name: "회철", location: "", rating: 5, quote: "위치가 정말 좋고, 아늑하면서도 넓은 공간이었습니다. 요청드린 새 이불과 수건도 빠르게 챙겨주셔서 편하게 지낼 수 있었어요. 이 지역에 다시 온다면 꼭 다시 묵고 싶습니다." },
            { name: "Sia", location: "", rating: 5, quote: "훌륭한 커뮤니케이션과 위치, 미니멀한 숙소를 원하는 1인에게 완벽한 숙소입니다." },
            { name: "Cho", location: "", rating: 5, quote: "매니저와 보조 관리자가 매우 도움이 되었습니다! 필요한 요청사항을 모두 친절하게 챙겨주셨고, 위치도 훌륭해서 필요한 모든 곳으로 편리하게 이동할 수 있습니다." },
            { name: "지혜", location: "", rating: 5, quote: "즐거운 숙박이었습니다. 공간이 넓고 아늑했어요. 책상, 좋은 와이파이, TV 등 필요한 것들이 잘 갖춰져 있어서 일하기에도 쉬기에도 좋았습니다." },
          ],
        },
        location: {
          eyebrow: "Location",
          title: "",
          desc: "",
          points: [
            "방배역 도보 약 1~2분",
            "강남권 이동이 편한 2호선 접근성",
            "사당역 환승 접근이 쉬워 서울 남북 이동도 무난",
            "편의점, 카페, 식당 모두 도보 1~2분 거리",
          ],
          sideTitle: "",
          sideBody: "",
        },
        faq: {
          eyebrow: "FAQ",
          title: "자주 하는 질문",
          items: [
            { q: "모든 객실이 1인실인가요?", a: "네. 모든 객실은 1인 전용으로만 운영합니다." },
            { q: "보증금은 얼마인가요?", a: "기본적으로 월세 1개월분 기준으로 안내합니다." },
            { q: "관리비나 공과금이 추가되나요?", a: "아니요. 관리비와 공과금은 별도 청구하지 않습니다." },
            { q: "가장 조용한 객실은 어디인가요?", a: "201 / 301 / 401호가 좌우 인접실이 없어 가장 조용한 축으로 안내됩니다." },
          ],
        },
        contact: {
          eyebrow: "Inquiry",
          title: "입실 문의",
          message: "카카오톡, 전화, 이메일 중 편한 채널로 문의해 주세요. 희망 입실 시기와 체류 기간을 알려주시면 가능한 호실을 안내해드립니다.",
          responseNote: "보통 1시간 이내 답변드립니다",
          channels: [
            { type: "kakao", label: "카카오톡", hint: "" },
            { type: "phone", label: "전화 문의", hint: "" },
            { type: "email", label: "이메일", hint: "" },
            { type: "naver", label: "네이버 예약", hint: "네이버에서 바로 예약" },
          ],
          form: {
            name: "이름",
            contact: "전화번호 또는 이메일",
            message: "문의 내용",
            placeholder: "희망 입주 시기, 체류 기간, 궁금한 호실을 적어 주세요.",
            consent: "개인정보 수집 및 문의 응답 목적 이용에 동의합니다.",
            submit: "문의 보내기",
            sending: "전송 중입니다...",
            success: "문의가 접수되었습니다. 가능한 객실 확인 후 빠르게 답변드리겠습니다.",
            error: "전송에 실패했습니다. 잠시 후 다시 시도해 주세요.",
          },
          mobileCtas: [
            { type: "kakao", label: "카카오톡" },
            { type: "phone", label: "전화 문의" },
            { type: "email", label: "이메일" },
            { type: "naver", label: "네이버 예약" },
          ],
        },
        footer: {
          copy: "",
          address: "",
          links: [
            { href: "#gallery", label: "사진" },
            { href: "#faq", label: "FAQ" },
            { href: "#contact", label: "문의" },
          ],
        },
      },
      en: {
        seo: {
          title: "Homestead Seoul | Private Rooms for Solo Travelers in Seoul",
          description: "Private single-occupancy rooms in Seoul with a private bathroom, furnished setup, and simple move-in for longer stays.",
          ogTitle: "Homestead Seoul | Furnished Private Rooms for Solo Travelers",
          ogDescription: "A calm Seoul base for solo travelers, exchange students, interns, and long-stay visitors.",
          locale: "en_US",
        },
        nav: [
          { href: "#quick-facts", label: "Quick Facts" },
          { href: "#gallery", label: "Gallery" },
          { href: "#included", label: "Included" },
          { href: "#testimonials", label: "Reviews" },
          { href: "#faq", label: "FAQ" },
          { href: "#contact", label: "Contact" },
        ],
        sections: ["hero", "trustStrip", "quickFacts", "gallery", "included", "testimonials", "location", "faq", "contact"],
        trustStrip: {
          items: [
            { icon: "manager", title: "On-site manager, 1st floor", desc: "Our manager on the first floor helps with check-in, check-out, and keeps the building secure." },
            { icon: "privacy", title: "Private bathroom, locking door", desc: "Every room has its own bathroom and lock for real privacy." },
            { icon: "reply", title: "Fast replies", desc: "Message us on KakaoTalk anytime — we usually reply within an hour." },
          ],
        },
        hero: {
          kicker: "Solo traveler stay · Furnished room · Seoul",
          title: "A private room in Seoul<br>2 min from Bangbae Station",
          subtitle: "Private room / Private bathroom / No hidden fees / Move in anytime",
          chips: ["Solo occupancy only", "Private bathroom", "Furnished essentials", "Subway access"],
          notes: ["From $19.99/day"],
          primaryAction: { href: "#contact", label: "Check availability" },
          secondaryAction: { type: "whatsapp", label: "WhatsApp" },
          tertiaryAction: { href: "#gallery", label: "See room photos" },
          carouselSlides: [
            { title: "A calm room to return to in Seoul" },
            { title: "Furnished for everyday solo living" },
            { title: "Privacy that fits a longer stay" },
          ],
        },
        quickFacts: {
          eyebrow: "Quick Facts",
          title: "",
          desc: "",
          items: [
            { label: "Price", value: "From $19.99/day", note: "B type room" },
            { label: "Deposit", value: "Refundable", note: "" },
            { label: "Monthly fees", value: "None", note: "" },
            { label: "Utilities", value: "Included", note: "" },
          ],
        },
        collections: {
          eyebrow: "Room Highlights",
          title: "Choose by what matters most to your stay",
          desc: "International guests often compare by feel first: quietness, layout, light, and ease of living.",
        },
        inventory: {
          eyebrow: "Room List",
          title: "Room-by-room overview",
          desc: "Each card explains what changes from room to room without relying on local housing jargon.",
          helper: "Use filters for quieter rooms, more space, rectangular layouts, or bathroom windows.",
          filters: [
            { id: "all", label: "All rooms" },
            { id: "quiet", label: "Quiet rooms" },
            { id: "spacious", label: "More space" },
            { id: "rectangle", label: "Rectangular layout" },
            { id: "window", label: "Bathroom window" },
          ],
          primaryCta: "Ask about this room",
          secondaryCta: "See pricing",
        },
        gallery: {
          eyebrow: "Gallery",
          title: "Room types and pricing at a glance",
          desc: "",
        },
        included: {
          eyebrow: "Included",
          title: "Most of what you need is already here",
          desc: "The basics are covered so you can start living from day one.",
          cards: [
            { icon: "bathroom", title: "Private bathroom", desc: "Every room includes its own private bathroom." },
            { icon: "laundry", title: "Washer, fridge, and microwave", desc: "A washing machine, refrigerator, and microwave are all included in every room." },
            { icon: "bed", title: "Bed, table, and basic supplies", desc: "You receive the basics needed to start living right away." },
          ],
        },
        pricing: {
          eyebrow: "Pricing",
          title: "Clear monthly pricing for solo stays",
          desc: "The English page uses an all-in monthly view because that is easier for international guests to trust and understand.",
          rows: [
            { tier: "S type room", rooms: "201 / 301 / 401 / 101 / 102", price: "$32.99/day ($999/month)", deposit: "Refundable incidental deposit", note: "The quietest and most spacious room type." },
            { tier: "A type room", rooms: "212 / 204 / 208 / 209 / 409", price: "$26.99/day ($799/month)", deposit: "Refundable incidental deposit", note: "Balanced, practical rooms for everyday long-stay use." },
            { tier: "B type room", rooms: "When available", price: "$19.99/day ($599/month)", deposit: "Refundable incidental deposit", note: "The most accessible private-room option." },
            { tier: "A+ type room", rooms: "205", price: "Quoted individually", deposit: "Refundable incidental deposit", note: "A quieter end-of-hall room between A and S types." },
          ],
          sideTitle: "Stay terms",
          sideBody: "The goal here is clarity before inquiry, so international guests know how the stay works and what to expect.",
          notes: ["Every room is for one person only.", "The monthly price does not add extra utility charges.", "A refundable incidental deposit applies.", "Room 205 is quoted individually."],
        },
        testimonials: {
          eyebrow: "Reviews",
          title: "What past guests have said",
          items: [
            { name: "Ganesh", location: "Lawrence, Massachusetts", rating: 5, quote: "The host was great with us from start to end — conveniently located, and everything we asked for was arranged without any trouble." },
            { name: "Zachary", location: "Baltimore, Maryland", rating: 5, quote: "Great host, very good communication and help with our stay! Would definitely stay again — very clean and tidy." },
            { name: "Davis", location: "Cartersville, Virginia", rating: 5, quote: "Wonderful location and a great stay!" },
            { name: "Jonathan", location: "Raleigh, North Carolina", rating: 5, quote: "This is my 2nd time staying here, and as before it was amazing — peaceful and quiet." },
            { name: "Breanna", location: "", rating: 5, quote: "Absolutely perfect stay! The hosts were super nice, and the place was comfortable and welcoming. Highly recommend staying here!" },
            { name: "Hugo", location: "Richmond, Virginia", rating: 5, quote: "The host was very attentive and kind. It was definitely a pleasant experience." },
          ],
        },
        location: {
          eyebrow: "Location",
          title: "A practical Seoul base near Bangbae Station",
          desc: "",
          points: [
            "1-2 min walk to Bangbae Station",
            "Line 2 access to Gangnam and beyond",
            "Easy transfer at Sadang Station",
            "Convenience stores, cafes, and restaurants all 1-2 min away",
          ],
          sideTitle: "",
          sideBody: "",
        },
        faq: {
          eyebrow: "FAQ",
          title: "Questions solo travelers often ask",
          items: [
            { q: "Is this a hotel or hostel?", a: "No, it's private single-occupancy rooms for longer stays." },
            { q: "Do I get my own bathroom?", a: "Yes. Every room includes a private bathroom." },
            { q: "Who is this best for?", a: "Solo travelers, interns, and exchange students staying longer term." },
            { q: "How do I reserve a room?", a: "Message us to confirm dates, then pay the deposit and first month's rent to book." },
            { q: "Are utilities extra?", a: "No. The monthly price does not add extra utility charges." },
            { q: "Can two people stay in one room?", a: "No. Every room is for single occupancy only." },
          ],
        },
        contact: {
          eyebrow: "Contact",
          title: "Ask about availability in the easiest way for you",
          message: "",
          responseNote: "Usually replies within 1 hour",
          channels: [
            { type: "email", label: "Email", hint: "Best for written details and date requests" },
            { type: "whatsapp", label: "WhatsApp", hint: "Fast for international messaging" },
            { type: "phone", label: "Phone", hint: "Direct contact when needed" },
          ],
          form: {
            name: "Name",
            contact: "Phone or email",
            message: "Message",
            placeholder: "Please share your dates, stay length, and any room preferences.",
            consent: "I agree to data collection for inquiry response.",
            submit: "Send inquiry",
            sending: "Sending...",
            success: "Inquiry received. We will reply with availability as soon as possible.",
            error: "Failed to send inquiry. Please try again shortly.",
          },
          mobileCtas: [
            { type: "whatsapp", label: "WhatsApp" },
            { type: "phone", label: "Call" },
            { type: "email", label: "Email" },
          ],
        },
        footer: {
          copy: "A calm, practical Seoul base for solo travelers who want a private room instead of a shared stay.",
          address: "",
          links: [
            { href: "#quick-facts", label: "Quick Facts" },
            { href: "#gallery", label: "Gallery" },
            { href: "#contact", label: "Contact" },
          ],
        },
      },
    },
  };

  window.HOMESTEAD_ADMIN_META = {
    key: ADMIN_OVERRIDE_KEY,
    allowedEmail: "homesteadseoul@gmail.com",
  };
  window.HOMESTEAD_DEFAULT_CONFIG = DEFAULT_CONFIG;
})();
